Added an empty placeholder to select a city
wppunk/shipping-nova-poshta-for-woocommerce pull request #99
Opened 2020-12-01 16:57 UTC by valko-pro

2020-12-01 16:58 UTC, valko-pro commented
![image](https://user-images.githubusercontent.com/22908236/100771548-34316580-3407-11eb-9db9-68d6b6fda065.png)

2020-12-01 18:16 UTC, wppunk requested changes

2020-12-01 18:16 UTC, wppunk commented on front/assets/js/main.js
> +					warehouse_wrapper.show();
move it to the next line after variables.

2020-12-01 18:16 UTC, wppunk commented on admin/class-user.php
>  		$warehouses   = $this->api->warehouses( $city_id );
What If empty `$city_id`?

2020-12-01 18:16 UTC, wppunk commented on admin/class-user.php
> +				'options'  => [ '' => '' ],
What for customers who have user_meta with the current warehouse? I don't want to choose these fields again :)

2020-12-01 18:16 UTC, wppunk commented on front/assets/css/main.css
> +#shipping_nova_poshta_for_woocommerce_warehouse_field {
Try to use:
```
#shipping_nova_poshta_for_woocommerce_city_field .select2-container,
#shipping_nova_poshta_for_woocommerce_warehouse_field .select2-container {
	display: block;
	width: 100%;
}
```

2020-12-01 19:49 UTC, valko-pro commented on front/assets/js/main.js
> +					warehouse_wrapper.show();
Okay

2020-12-01 19:50 UTC, valko-pro commented on admin/class-user.php
>  		$warehouses   = $this->api->warehouses( $city_id );
You said that we have city id always )))

2020-12-01 19:50 UTC, valko-pro commented on admin/class-user.php
> +				'options'  => [ '' => '' ],
Okay

2020-12-01 19:50 UTC, valko-pro commented on front/assets/css/main.css
> +#shipping_nova_poshta_for_woocommerce_warehouse_field {
And max-width)

2020-12-02 11:56 UTC, wppunk requested changes
Check my comments

2020-12-02 11:56 UTC, wppunk commented on admin/class-user.php
>  		$warehouse_id = filter_input( INPUT_POST, 'shipping_nova_poshta_for_woocommerce_warehouse', FILTER_SANITIZE_STRING );
Add `$warehouse_classes = [];`

2020-12-02 11:56 UTC, wppunk commented on admin/class-user.php
>  		}
```
$warehouse_id      = apply_filters(
	'shipping_nova_poshta_for_woocommerce_default_warehouse_id',
	$warehouse_id,
	$user_id,
	$city_id
);
```

2020-12-02 11:56 UTC, wppunk commented on admin/class-user.php
>  		}
`$warehouses   = [ '' => '' ];`

2020-12-02 11:56 UTC, wppunk commented on admin/class-user.php
> +			$warehouse_id      = array_keys( $warehouses )[0] ?? '';
Remove `$warehouse_id` from this `if`

2020-12-02 11:56 UTC, wppunk commented on admin/class-user.php
> +		} else {
Remove `else`

2020-12-02 11:56 UTC, wppunk commented on admin/class-user.php
> +				'default'  => $warehouse_id,
`isset( $warehouses [ $warehouse_id ] ) ? $warehouse_id : '';`

2020-12-15 08:41 UTC, closed without merging